### ISSUE TITLE
QA testing for https://github.com/microsoft/workshop-library/blob/main/rest-apis/README.md

### ISSUE THREAD

**Issue by jlooper** [microsoft/workshop-library#30]
- [x] All elements of the workshop are in place (README, workshop designer, solution if necessary, any images if necessary, slides, a call-to-action with a Learn module linked (usually in "Next Steps" area), a knowledge check (either in slides or directly linked to the workshop README) and an area to extend knowledge.
- [x] The workshop can be done in its listed time frame
- [x] Instructions are clear and well written
- [x] The workshop is bug-free
- [x] The workshop 'flows' well

**Comment by sheki018** [comment]
- [x] All elements of the workshop are in place (README, workshop designer, solution if necessary, any images if necessary, slides, a call-to-action with a Learn module linked (usually in "Next Steps" area), a knowledge check (either in slides or directly linked to the workshop README) and an area to extend knowledge.
 - [x]  The workshop can be done in its listed time frame
 - [x]  Instructions are clear and well written
 - [x]  The workshop is bug-free
 - [x]  The workshop 'flows' well
 
**Suggestions:**
The prerequisites for the workshop as stated in the README file is only a modern browser but the slides contain a couple of other prerequisites also like node and npm. I think this is because the slide also has a section on how to build a local API which isn't covered in the README file. I also feel that the slide which explains "what is an API?" can be modified with more relatable content for the audience to understand it easily.

**Comment by jlooper** [comment]
Thank you, I will fix up the slides!

**Comment by jlooper** [comment]
done and posted! thank you!
