### ISSUE TITLE
[github.dev] - your own repo?

### ISSUE THREAD

**Issue by johnpapa** [microsoft/workshop-library#32]
The lesson we're teaching is how to use github basic features in github.dev. Should the lesson operate on a repo that isnt owned by the workshop attendee or should it operate on a repo they do own? If the former, then they wont be able to merge the PR. If the latter, then they can merge the PR but we need to give them a repo (perhaps have them use a template repo as an example).

Curious what you think

**Comment by jlooper** [comment]
In the instructions, we ask folks to:

Fork this repo (the workshop library itself) to their own GH account, then make a branch on their own repo, make and edit, and merge to their own main branch. So we are following the 'latter' suggestion.

The problem I have (correlated by Student Ambassadors) is we can't seem to do that merge process in GitHub.dev.

**Comment by johnpapa** [comment]
I'm not addressing a merge issue, more of a steps question for what is best for repo creation for the learner.

What would be the pros and cons be for forking vs a creating from a template?

**Comment by jlooper** [comment]
This workshop library is a template, but we ask students to fork it (rather than clicking 'use this template') and work on their own copy. 

Is it confusing to ask users to fork a repo that is also a template? I don't think so, as the fork option remains available as per the usual. We want to point students towards the most common use case that they might meet in the real world.

The history behind this decision is that the Learn module I originally based this workshop on used a public template called "https://github.com/firstcontributions/first-contributions" - and that repo uses a 'master' branch as its main repo. It's also not a MSFT repo at any rate. So we don't want to point users to that experience. So we came up with the idea of using this repo (the workshop-library) instead. I believe the path we send students down (fork > branch > edit the fork > PR to the user's own main branch) is legitimate.

About the merge issue...just tested creating a copy of this repo using the 'use this template' button and I have the same problem as when I fork

**Comment by johnpapa** [comment]
Thanks for the reply.

Perhaps create a new issue for the merge problem?
